# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

u1 = User.create(first_name: "Kobe", last_name: "Bryant", email: "kbryant@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Los Angeles", school: "Lakers", position: "Small Guard",  image:"http://www.trbimg.com/img-5450096b/turbine/la-sp-ln-lakers-byron-scott-kobe-bryant-20141028", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u2 = User.create(first_name: "Steve", last_name: "Kerr", email: "skerr@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "coach", image: "http://palisadesparade.org/wordpress/wp-content/uploads/2014/06/Steve-Kerr1.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u3 = User.create(first_name: "Stephen", last_name: "Curry", email: "scurry@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "point guard", facebook:"https://www.facebook.com/StephenCurryOfficial", linkedin: "http://linkedin.com", instagram: "https://instagram.com/wardell30/", twitter: "https://twitter.com/stephencurry30", image: "http://www.gannett-cdn.com/-mm-/9b82493af6d6321ddc22c7a31e72b33309d7a36f/c=1275-0-2925-2200&r=537&c=0-0-534-712/local/-/media/2015/02/14/USATODAY/USATODAY/635595490453065957-2015-02-14-Stephen-Curry1.jpg" , about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u4 = User.create(first_name: "Klay", last_name: "Thompson", email: "kthomspon@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small guard", image: "http://shandyfiles.s3-us-west-1.amazonaws.com/images/photos/thefumble/klay-thompson-scores-26-in-second-quarter.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u5 = User.create(first_name: "Andre", last_name: "Iguodala", email: "aiguodala@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors",position: "small guard", image: "http://www4.pictures.zimbio.com/gi/Andre+Iguodala+Spain+v+USA+INUhVbxqhlUl.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u6 = User.create(first_name: "David", last_name: "Lee", email: "dlee@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "power forward", image: "http://thesportsquotient.com/media/posts/16774/david%20lee.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u7 = User.create(first_name: "Draymond", last_name: "Green", email: "dgreen@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small forward", image: "http://www4.pictures.zimbio.com/gi/Draymond+Green+Chicago+Bulls+v+Golden+State+_NsXbWi0rdNl.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u8 = User.create(first_name: "Andrew", last_name: "Bogut", email: "abogut@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "center",image: "http://warriorsworld.bayareaballllc1.netdna-cdn.com/wp-content/uploads/2014/01/Andrew-Bogut.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u9 = User.create(first_name: "Shaun", last_name: "Livingston", email: "slivingston@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "point guard", image:"http://i.cdn.turner.com/drp/nba/warriors/sites/default/files/livingston_okc_20141218.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u10 = User.create(first_name: "Harrison", last_name: "Barnes", email: "hbarnes@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small forward", image:"http://www1.pictures.zimbio.com/gi/Harrison+Barnes+2012+NBA+Rookie+Photo+Shoot+4OCFXyO64dql.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u11 = User.create(first_name: "Leandro", last_name: "Barbosa", email: "lbarbosa@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small guard", image:"http://thumb.usatodaysportsimages.com/image/thumb/650-510nw/8379908.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u12 = User.create(first_name: "Festus", last_name: "Ezeli", email: "fezeli@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "center", image:"http://www2.pictures.zimbio.com/gi/Golden+State+Warriors+v+Los+Angeles+Lakers+K7tzvJTm9zvl.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u13 = User.create(first_name: "Marreese", last_name: "Speights", email: "mspeights@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "center", image:"http://ww1.hdnux.com/photos/33/24/11/7160408/11/920x920.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u14 = User.create(first_name: "Brandon", last_name: "Rush", email: "brush@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small guard", image:"http://l.yimg.com/j/assets/p/sp/getty/ec/fullj.fae835ba328d8c884ab981ca8c80c763/fae835ba328d8c884ab981ca8c80c763-getty-136725986.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
u15 = User.create(first_name: "James", last_name: "McAdoo", email: "jmcadoo@warriors.com", password: "pa55w0rd", password_confirmation: "pa55w0rd", code: "gapinc", location: "Golden State", school: "warriors", position: "small guard", image:"http://thumb.usatodaysportsimages.com/image/thumb/650-510nw/8521826.jpg", about: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodoconsequat. Duis aute irure dolor in reprehenderit in voluptate velit essecillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat nonproident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

g1 = Global.create(first_name: "Art", last_name: "Peck", email: "art_peck@gap.com", image: "http://www.gapinc.com/content/dam/gapincsite/images/bio/HIRES_bio_Art_Peck.jpg", position: "Chief Executive Officer", about: "Art Peck is Gap Inc.'s Chief Executive Officer. He joined Gap Inc. in 2005 and has held senior leadership positions across nearly every area of the company.From 2012 to January 2015, Art served as President of the company’s Growth, Innovation and Digital (GID) division, with responsibility for the digital strategy of our more than $2 billion e-commerce business across the 80 countries where the company serves customers online. He drove the innovation agenda for the company across its digital platforms and more than 3,000 stores around the world. Ultimately, Art and his team developed and deployed the industry-leading, omni-channel platform for consumers to bridge the physical and digital shopping experience.
In this broad operating role, Art guided the growth of the emerging brands Athleta, Piperlime and Intermix, which is particularly fitting given he led the internal efforts to acquire Athleta, in 2008, and Intermix, in 2012. Art also added responsibility for the Gap Inc. technology division, working closely with the company’s chief information officer to optimize innovative and business solutions.

In his prior role, Art served as president of Gap North America, with its fleet of more than 700 stores, from February 2011 to November 2012. A product resurgence during this period drew customers back to the company’s namesake brand and helped improve the division’s sales performance for six consecutive quarters during his tenure and thereafter.

Previously, from 2008 to 2011, Art led the Outlet division, delivering strong sales and earnings growth for the value expressions of Gap and Banana Republic. Among the strategic shifts during this time, the division expanded globally, including first-ever Outlet store openings in Canada and Europe.
Art joined the company as executive vice president of Strategy & Operations, and he made an immediate impact by launching the company’s first franchise business, which now has grown to about 400 Gap, Banana Republic and Old Navy franchise stores in 40 countries. It was during this time that Art and CEO Glenn Murphy worked together to orchestrate the company’s China entry and architect the company’s current global growth strategy.

A champion of the company values to “do more than sell clothes,” Art has been a trustee on the board of Gap Foundation since 2008, and a long-time advocate for corporate social responsibility and the company’s philanthropic work. He played an integral role in Gap’s partnership with Product (RED) in 2006, in which a portion of product sales went to HIV/AIDS prevention efforts in Africa, and was a key supporter of the company’s decision in February 2014 to raise its minimum wage for U.S. employees.")
g2 = Global.create(first_name: "Sabrina", last_name: "Simmons", email: "sabrina_simmons@gap.com", image: "SabrinaSimmons.jpg", position: "EVP and Chief Financial Officer, Gap Inc.", about: "Sabrina Simmons is Executive Vice President and Chief Financial Officer of Gap Inc. In this role, she oversees real estate, loss prevention and all global financial departments, including controllership, corporate financial planning and analysis, investor relations, treasury, tax, risk management, internal audit and the corporate shared service center, and also has accountability for brand finance along with the company's brand presidents. Since joining Gap Inc. in 2001, Sabrina has progressed through positions of increasing responsibility from vice president and treasurer to executive vice president. Simmons was appointed CFO in January 2008.During her tenure, she has been instrumental in instilling financial discipline throughout the organization and developing the capital structure framework that has delivered increasing shareholder distributions while maintaining a strong balance sheet.
Before coming to Gap, Sabrina was chief financial officer and an executive member of the Board of Directors of Sygen International PLC, a British genetics company. Prior to Sygen, Simmons spent five years at Levi Strauss & Co., where she was assistant treasurer. She also spent several years at Hewlett Packard Company and KPMG.Sabrina received her B.S. in Finance from the University of California, Berkeley where she was also bestowed the award of Regent Scholar, and received her M.B.A. from the Anderson School at the University of California, Los Angeles. Sabrina currently serves on the Haas School of Business Advisory Board. Sabrina is a member of the Gap Foundation Board of Trustees.")
g3 = Global.create(first_name: "Andi", last_name: "Owen", email: "andi_owen@gap.com", image: "AndiOwen", position: "Global President, Banana Republic", about: "Andi Owen is Global President for Banana Republic, where she is responsible for managing all markets and channels for Banana Republic around the world.
Prior to this, Andi served as executive vice president and General Manager of Global Gap Outlet, responsible for the value expression of Gap brand across North America, Europe and Asia.

During her time with Gap Outlet, Andi and her team grew the business, expanded its reach beyond traditional outlet malls with the addition of urban locations.
Andi has more than twenty-five years of apparel industry experience and is known for her strategic vision and commitment to developing world-class teams. She began her Gap Inc. career in 1991 and has held various leadership positions across the company including, SVP & GM for Banana Republic Factory Store, Divisional Merchandise Manager at Gap Inc. Direct for Old Navy, GM for Banana Republic Canada, and a variety of positions within the Banana Republic field organization, including Western Zone VP. 

Prior to joining Gap Inc., Andi worked for Bloomingdales where she held several cross-functional positions.

Andi holds a B.A. in Art History from the College of William and Mary.
Andi serves on the Gap Inc. Foundation Board. She is passionate about volunteering, giving back to the community and mentoring. ")
g4 = Global.create(first_name: "Stefan", last_name: "Larsson", email: "stephan_larsson@gap.com", image: "StefanLarsson.jpg", position: "Global President, Old Navy", about: "Stefan Larsson is the Global President of Old Navy, a division of Gap Inc.
He joined Gap Inc. in 2012 after a highly successful career at Swedish retailer, Hennes & Mauritz (H&M), spanning nearly 15 years where he was a part of the team responsible for growing H&M, with revenues increasing from about $3 billion to about $17 billion and operations expanding from 12 to 44 countries. 
He most recently served as head of Global Sales with functional responsibility for about 2,300 stores and nearly all of the company’s $17 billion in annual sales. This role, which reported to the CEO, encompassed all aspects of the business that are customer-facing: product merchandising, visual merchandising, store operations, store design and development, inventory management, and customer service. 

Previously, Stefan was responsible for overseeing H&M’s global expansion, with responsibility for real estate, store design and store construction. Earlier in his career at H&M, he lived in California and led the company’s launch of H&M on the West Coast of the United States, and spent nearly seven years in numerous global roles with responsibility for product, including merchandising, assortment development, planning and production for the company. 

Stefan earned a Master of Science in Business Administration jointly from the Swedish School of Economics and Business Administration, in Finland, and Jonkoping International Business School, in Sweden.")
g5 = Global.create(first_name: "Nancy", last_name: "Green", email: "nancy_green@gap.com", image: "NancyGreen.jpg", position: "President and General Manager, Athleta", about: "Nancy Green is currently President and General Manager of Athleta, leading the brand through a high-growth phase and brand evolution.

Throughout her three decades of retail, leading high growth businesses and teams have been her expertise along with creating and developing brand vision, strategy, and breakthrough product and marketing. She is also known as an impactful mentor of talent who has developed strong leaders across the industry. She has worked for Gap Inc. for 21 years over two phases, including her first 16 years in retail and most recent 5 years since rejoining the company in 2009.

Prior to joining Athleta in 2013, she served as EVP and Chief Creative Officer at Old Navy, leading the merchandising, design and visual merchandising teams. Under her leadership, the brand focused on balancing innovation in core categories while launching new and expanding businesses. Nancy served as interim co-leader of Old Navy in 2012.

Previously, Green served as CEO of Shabby Chic, where she partnered with the founder to create and implement a vision and growth strategy for a multi-channel lifestyle brand. She facilitated its expansion into new categories and distribution channels while overseeing all areas of the company.

In addition, she ran the Pottery Barn division of Williams-Sonoma, Inc as executive vice president from 2003-2007 where she led a multi-channel business (online, catalog, stores) through a significant growth phase expanding into new categories and developing the online business into a major channel.

She spent 16 years at Gap Inc from 1986-2002 overseeing merchandising in a variety of divisions, including Gap brand both within the US and globally, as well as the kids and baby division for Old Navy.
She holds a BA from University of California, Berkeley.")
g6 = Global.create(first_name: "Jyothi", last_name: "Rao", email: "jyothi_rao@gap.com", image: "http://static1.1.sqspcdn.com/static/f/1337919/25260466/1406733481737/Jyothi+Rao_blog.jpg?token=HPCaB8uTI4xkeT62ziN14MtzM1w%3D", position: "President and General Manager, Intermix", about: "Jyothi brings extensive experience in the retail sector to her role as President of INTERMIX. She is responsible for crafting the vision for the brand and for developing the overall business strategy.
Prior to joining INTERMIX in 2014, Jyothi served as Executive Vice President and General Manager of Gilt.com where she was instrumental in growing the business into a leading digital fashion site. Before Gilt, Jyothi served as Senior Vice President and General Manager at Calvin Klein, where she launched the Specialty Retail division.
Previously, Jyothi spent 16 years at Gap Inc., where she held several leadership positions and was responsible for successfully growing domestic and international businesses for both the Gap and Banana Republic brands. Jyothi has resided in Africa, India, and Europe.")
g7 = Global.create(first_name: "Sol", last_name: "Goldfarb", email: "sol_goldfarb@gap.com", image: "SolGoldfarb.jpg", position: "EVP, Digital & Customer Experience, Gap Inc.", about: "Sol Goldfarb is Executive Vice President, Digital and Customer Experience for Gap Inc. In this role, Sol is responsible for guiding the strategy and delivery of innovative technology that delights customers and bridges the divide between the physical and digital shopping experiences.
Sol has been at the center of the transformation of the retail customer shopping experience for the last two decades. Joining the Growth, Innovation and Digital Division in 2004 to oversee product management, Sol has progressed through the organization touching every part of Gap Inc.’s digital landscape. Sol is now responsible for driving the company’s overall technology agenda across five global brands. During his tenure, Sol has brought the company’s e-commerce business to international markets, developed the digital expression for new brands the company has started and acquired, pivoted the organization’s efforts to take advantage of the huge growth in customer use of mobile devices, and driven the development of best-in-class omni-channel offerings, like Find In Store, Ship From Store, Reserve In Store and Order In Store.
Sol came to Gap Inc. from AOL/Netscape, where he led some of the Internet’s most impactful technology innovations. Chief among his accomplishments was the strategic oversight of AOL Music, which included Radio@AOL, AOL Media Player, Video@AOL and Winamp. Sol was also responsible for the development of Netscape 6.1 and 6.2 and Netscape’s line of retail products, including Netscape Communicator and Netscape Publishing Suite.
Sol earned his J.D. from Harvard Law School and practiced law for several years, with a focus on corporate counsel and venture capital fund representation, before refocusing his career to follow his passion for technology innovation and strategy.")
g8 = Global.create(first_name: "Michelle", last_name: "Banks", email: "michelle_banks@gap.com", image: "MichelleBanks.jpg", position: "EVP, Global General Counsel, Corporate Security & Chief Compliance Officer, Gap Inc.", about: "Michelle Banks is Executive Vice President, Global General Counsel, Corporate Secretary & Chief Compliance Officer of Gap Inc.

In addition to the global legal function, Michelle currently oversees the Company’s global equity, integrity and privacy functions. She has also led the foundation, franchise services, government affairs & public policy and sustainability functions during her tenure at Gap Inc.

Before joining the Company in 1999, Michelle was in-house legal counsel for the NBA’s Golden State Warriors, and prior to that, worked in Japan as American counsel for ITOCHU Corporation. She was also associated with several law firms, including Morrison & Foerster in California and New York, focusing on corporate finance and international commercial transactions.

Michelle graduated from UCLA with degrees in Law and Economics, and was admitted to the California bar in 1988. She serves as Chair of the Board of Directors of Minority Corporate Counsel Association and on the American Bar Association’s Commission on Women in the Profession.")
g9 = Global.create(first_name: "Bobbi", last_name: "Silten", email: "bobbi_silten@gap.com", image: "BobbiSilten.jpg", position: "EVP, Global Talent & Sustainability", about: "Bobbi Silten is Executive Vice President, Global Talent and Sustainability. In this role, Bobbi oversees social and environmental sustainability; human resources; government affairs, corporate communications and Gap Foundation.

Since 2005, she has led Gap Foundation, overseeing its global community investments in women’s advancement and youth first jobs, and volunteer programs for employees worldwide. 

In early 2011, she was tapped to lead Gap Inc.’s Global Sustainability practice – encompassing vendor monitoring and capability building, environmental sustainability, global stakeholder partnerships and sustainable innovation.

In 2011-2012, she served as a member of the White House Council for Community Solutions, which provided advice to President Obama on the best ways to mobilize citizens, nonprofits, businesses and government to work more effectively together to solve specific community needs. She co-led the Youth Employment Program working group, which developed the Connecting Youth & Business toolkit.

She was a founding member of Reimagining Service, a five-year national cross-sector initiative to increase the impact of volunteerism, and served as the chair of the Reimagining Service Council until 2014.

She serves on the Leadership Council for Opportunity Nation and is also a volunteer mentor to alumni of Summer Search, a national youth leadership program.
Prior to joining Gap Inc., Silten spent 10 years at Levi Strauss & Co., including five years as President of the U.S. Dockers brand. She started her professional career in advertising and has a bachelor’s degree from the University of California, Berkeley.")


b1 = Brand.create(name: "Gap", banner: "gap_banner.png", logo: "gap_logo.png", description: "

<p>Clean. Classic. American design. These words described Gap four decades ago and still hold true today. </p>

<p>At our best, we inspire customers with individual style and make classics relevant for today through our use of bold color, emotional details and great fits.
With a clear brand vision and effortlessly cool product, Gap is re-connecting with its target customer—men and women ages 25 to 35 looking to express their unique, personal style. </p>

<p>Across each Gap sub-brand, we continue to evolve our assortments with a focus on what we’ve always been famous for: the best of casual style.</p>

<p>More than anything, though, Gap has been known for its connection to pop culture. In 2008, Gap launched innovative and relevant campaigns such as the Artist Edition T-shirts, showcasing designs by distinguished artists, and our non-partisan VOTE campaign, timed to coincide with the historic U.S. presidential election. </p>

<p>Innovation extends to our GapKids and babyGap businesses, as well. The launch of babyGap home products and the popular Junk Food graphic T-shirts helped bring fresh choices to our customers. And, we added GapBody collections to more than 500 stores.</p>

<p>As we celebrate our 40-year heritage, Gap is committed to staying relevant by continuing to give our customers Gap classics, invented and re-invented for right now. </p>")

b2 = Brand.create(name: "Old Navy", banner: "on_banner.png", logo: "on_logo.png", description: "

<h2>Brand Platform</h2>
<p>Imagine a place where you can find all of your wardrobe 'must-have's' at prices you can’t believe. Everything from your favorite t-shirts and jeans to your seasonal fashion faves. A place where every family member is invited no matter what their size. Where everything has great style and quality and the shopping experience is actually fun, not a chore. That place is Old Navy. Making current American fashion essentials accessible to every family.</p>

<p><b>Founded:</b> 1994 (named after a bar in Paris)<p>
<p><b>Retail record:</b> In 1997, became first retailer to reach $1 billion in annual sales in less than four years of operation.</p>

<h2>What to Expect Your First Couple Days</h2>

<p>To get to know Gap Inc and Old Navy, you will experience two days of on-boarding. The first day will be about Gap Inc and all its brands, and the second day will be specific to Old Navy. If you are part of Design, Merchandising, Inventory Management or Production, and are attending the Product Team On boarding:<p>

<ul>
<li><b>Monday:</b> You’ll meet and mingle with other Gap Inc employees at 2 Folsom for an all day experience.</li>
<li><b>Tuesday:</b> In the morning you’ll participate in a cross-brand Product Team on-boarding. Then… on to the bus to Mission Bay for lunch followed by an afternoon of discovery about Old Navy and who our target customers are -- Jennie, Mike and the Kids. Meet us at 2pm in front of the “Jennie, Mike and the Kids” poster to begin your deep dive into Old Navy.</li>
</ul>

<p>If you are not part of Design, Merchandising, Inventory Management or Production:</p>

<ul>
<li><b>Monday:</b> You’ll meet and mingle with other Gap Inc employees at 2 Folsom for an all day experience.</li>
<li><b>Tuesday:</b> Your manager will let you know what time and where to show up on Tuesday morning. If you haven’t heard from your hiring manager yet, reach out to them directly for these details. In the afternoon you’ll have an afternoon of discovery about Old Navy and who our target customers are -- Jennie, Mike and the Kids. Meet us at 2pm in front of the “Jennie, Mike and the Kids” poster to begin your deep dive into Old Navy.</li>
</ul>")

b3 = Brand.create(name: "Intermix", banner: "intermix_banner.png", logo: "intermix_logo.png", description: "

<p><b>INTERMIX</b> is a multi-brand fashion retailer with a compelling and unique point-of-view. INTERMIX offers a curated mix of on-trend, irresistible pieces that celebrate each customer’s personal sense of style with an intimate, individualized approach at more than 30 boutiques across the United States and Canada and online at www.intermixonline.com. The assortment focuses on the most exciting fashion trends and the finest mix of emerging and established designers.</p>

<p><b>INTERMIX</b> is regarded for its philosophy of mixing fashionable pieces in unexpected ways, offering the most coveted designers and sought-after styles from the industry’s best brands. In addition to its vast array of seasonal must-haves, INTERMIX sets itself apart by offering a broad array of exclusive designer products. The brand was acquired by Gap Inc. in December 2012.</p>")

b4 = Brand.create(name: "Banana Republic", banner: "br_banner.png", logo: "br_logo.png", description: "

<p>Banana Republic brings a fresh twist on classic apparel to men and women around the world. The company that started as a safari outfitter in San Francisco now outfits a whole new generation of explorers in clothes that walk the line between easy and refined.</p>

<p>Our promise is to be the “True Outfitters of Modern American Style.” And through this, we’ll enable our customers to live their True Style. We believe that True Style is more than what you wear. It reflects how you live, how you choose to navigate your life, and how you show up.</p>")

b5 = Brand.create(name: "Athleta", banner: "athleta_banner.png", logo: "athleta_logo.png", description: "

<p>We have been the premier fitness apparel brand exclusively for women since 1998.</p>

<p>As athletes ourselves, we live a life in motion. That’s why we design versatile and fashionable performance apparel for the gym, studio and everything in between.</p>

<p>A woman athlete is her most powerful self when she’s fully engaged in the moment – when she discovers her strength, her focus, her power. We design products that live up to the challenges those moments bring and make her look as amazing as she feels.</p> 

<p>We understand that fitness is her oxygen and, for her, the joy is always in the doing. Power to the She.</p>")



